version: 2
updates:

  # Maintain dependencies for Docker Images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/dependabot"
    reviewers:
      - "rancher/k3s"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      action-deps:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"
    labels:
      - "kind/dependabot"
    reviewers:
      - "rancher/k3s"